// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REDACTED_FIREBASE_API_KEY',
    appId: '1:148161891333:web:default-web-app-id',
    messagingSenderId: '148161891333',
    projectId: 'jaamattime',
    authDomain: 'jaamattime.firebaseapp.com',
    storageBucket: 'jaamattime.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REDACTED_FIREBASE_API_KEY',
    appId: '1:148161891333:android:68547dfcc1ea57b5f8e06c',
    messagingSenderId: '148161891333',
    projectId: 'jaamattime',
    storageBucket: 'jaamattime.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REDACTED_FIREBASE_API_KEY',
    appId: '1:148161891333:ios:8be90a38cf4125e3f8e06c',
    messagingSenderId: '148161891333',
    projectId: 'jaamattime',
    storageBucket: 'jaamattime.firebasestorage.app',
    iosBundleId: 'com.example.jamaatTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REDACTED_FIREBASE_API_KEY',
    appId: '1:148161891333:ios:8be90a38cf4125e3f8e06c',
    messagingSenderId: '148161891333',
    projectId: 'jaamattime',
    storageBucket: 'jaamattime.firebasestorage.app',
    iosBundleId: 'com.example.jamaatTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REDACTED_FIREBASE_API_KEY',
    appId: '1:148161891333:android:68547dfcc1ea57b5f8e06c',
    messagingSenderId: '148161891333',
    projectId: 'jaamattime',
    storageBucket: 'jaamattime.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'REDACTED_FIREBASE_API_KEY',
    appId: '1:148161891333:android:68547dfcc1ea57b5f8e06c',
    messagingSenderId: '148161891333',
    projectId: 'jaamattime',
    storageBucket: 'jaamattime.firebasestorage.app',
  );
}
